name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"
          registry-url: https://registry.npmjs.org/

      - name: cache maven deps
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: maven

      - name: cache shadow-cljs
        uses: actions/cache@v1
        with:
          path: "**/.shadow-cljs"
          key: ${{ runner.os }}-shadow-cljs-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-shadow-cljs-

      - name: cache npm deps
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm i -g lerna
      - run: npm i -g yarn

      # - uses: DeLaGuardo/clojure-lint-action@v1
      #   with:
      #     clj-kondo-args: --lint packages/common/src
      #     github_token: ${{ secrets.GITHUB_TOKEN }}

      # - uses: DeLaGuardo/clojure-lint-action@v1
      #   with:
      #     clj-kondo-args: --lint packages/common/src
      #     github_token: ${{ secrets.GITHUB_TOKEN }}

      # - uses: DeLaGuardo/clojure-lint-action@v1
      #   with:
      #     clj-kondo-args: --lint packages/common/src
      #     github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: bootstrapping lerna
        run: lerna bootstrap

      - name: building
        run: lerna run build
